import type { ComponentType } from 'react';
import Home from './pages/Home';

export interface RouteDef {
  /** URL path, e.g. "/about-us/our-story". */
  path: string;
  /** Full <title> for the page. */
  title: string;
  /** Meta description. */
  description: string;
  Component: ComponentType;
}

/**
 * Every public page of the site, used by both the client router and the
 * prerender script (so each page becomes a real static HTML file).
 *
 * Section subagents: create `src/sections/<name>.ts` exporting `RouteDef[]`,
 * e.g.:
 *
 *   // src/sections/puppies.ts
 *   import type { RouteDef } from '../routes';
 *   import AvailablePuppies from '../pages/puppies/AvailablePuppies';
 *   export const puppyRoutes: RouteDef[] = [
 *     {
 *       path: '/puppies/available-puppies',
 *       title: 'Available Puppies | The Doghouse QLD',
 *       description: '...',
 *       Component: AvailablePuppies,
 *     },
 *   ];
 *
 * Do NOT edit this file; the wiring pass merges section files in `allRoutes`.
 */
import { aboutRoutes } from './sections/about';
import { puppyRoutes } from './sections/puppies';
import { dogRoutes } from './sections/dogs';
import { cavoodleRoutes } from './sections/cavoodles';
import { trainingDeliRoutes } from './sections/training-deli';
import { resourceRoutes } from './sections/resources';
import { legalRoutes } from './sections/legal';

const homeRoutes: RouteDef[] = [
  {
    path: '/',
    title: 'The Doghouse QLD - Thoughtfully Bred, Beautifully Raised Cavoodles',
    description:
      'The Doghouse QLD is a specialist multi-generational Cavoodle breeder in Queensland, Australia. Thoughtfully bred. Beautifully raised.',
    Component: Home,
  },
];

/** Section landing hubs (title/cards generated from nav.ts). */
export const hubPaths = ['/about-us', '/puppies', '/our-dogs', '/cavoodles', '/resources'];

export const hubMeta: Record<string, { title: string; description: string }> = {
  '/about-us': {
    title: 'About Us | The Doghouse QLD',
    description: 'Get to know The Doghouse QLD, our philosophy and our approach to health testing.',
  },
  '/puppies': {
    title: 'Puppies | The Doghouse QLD',
    description: 'Our puppies and litters, how we raise them, and how to apply.',
  },
  '/our-dogs': {
    title: 'Our Dogs | The Doghouse QLD',
    description: 'Meet the dogs at the heart of The Doghouse QLD.',
  },
  '/cavoodles': {
    title: 'Cavoodles | The Doghouse QLD',
    description: 'Learn about the Cavoodle breed we specialise in.',
  },
  '/resources': {
    title: 'Resources | The Doghouse QLD',
    description: 'Guides, answers and support for Doghouse families.',
  },
};

export const allRoutes: RouteDef[] = [
  ...homeRoutes,
  ...aboutRoutes,
  ...puppyRoutes,
  ...dogRoutes,
  ...cavoodleRoutes,
  ...trainingDeliRoutes,
  ...resourceRoutes,
  ...legalRoutes,
];
